### ISSUE TITLE
Release 1.3.8 .exe triggers virus warning

### ISSUE THREAD

**Issue by bdery** [zumoshi/BrowserSelect#31] opened 2018-03-13 15:21 UTC
On Virus Total, see report here:

https://www.virustotal.com/#/file/a667b215f3903a165c20f0805a110f74b2a41b5d836fd6bf671bafcf797fb769/detection

False alarm probably, but how can I increase my trust level ?

**Comment by zumoshi** [comment] 2018-03-13 15:24
duplicate of #19, if it was another anti-virus I might've done something about it, but Baidu is not very reliable.

if you don't trust the binary version you can always compile from the source code.

**Comment by bdery** [comment] 2018-03-13 20:05
Thanks ok makes sense. I'm back on Windows after many years on a Mac, so I prefer to be cautious for now until I get more comfortable with Windows again... I often use Sandboxie for trying out things more safely but since the point of this tool is to integrate tightly with the OS' handling of links then it's pointless to "sandbox" this one ;-)  Thanks for the info...

**Closed** 2018-03-13 20:07 UTC

**Comment by JeffGillman** [comment] 2018-03-13 23:05
bdery, I understand the frustration. Nothing is simple, is it? This is a good read about AV programs and false hits: http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/ 
I usually consider up to 3 hits false hits, unless one is from a better-known AV engine.
