### ISSUE TITLE
DataGridViewComboBoxCell value is not valid

### ISSUE THREAD

**Issue by igvk** [zumoshi/BrowserSelect#51] opened 2019-07-21 21:56 UTC
Here is the error I get:
DataGridView Default Error Dialog
The following exception occurred in the DataGridView:
System.ArgumentException: DataGridViewComboBoxCell value is not valid.
To replace this default dialog please handle the DataError event.

Probably due to changing Firefox install path.
Now I am unable to change Settings - the error is reappearing after dismissing.

**Comment by zumoshi** [comment] 2019-07-22 04:04
Hi,

Yes, the current version doesn't handle a browser used for rules being uninstalled/changed very well.
Until an update is released to fix this issue you can manually edit the following file as a workaround:

`C:\Users\[USERNAME]\AppData\Local\BrowserSelect\BrowserSelect.exe_Url_4j4dimlkqsgapflatinf2e2ay1t1qfzx\1.4.0.0\user.config`

Look for a section like this inside the file:

```xml
<setting name="AutoBrowser" serializeAs="Xml">
    <value>
        <ArrayOfString xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
             <string>*.reddit.com[#!][$~][?_]Chrome</string>
        </ArrayOfString>
    </value>
</setting>
```

Then find the line that has the old browser and remove it.

I'm going to close this issue because it's a duplicate of #46 .

**Closed by zumoshi** 2019-07-22 04:04 UTC
