### ISSUE TITLE
Setting Default Programs for HTTPS protocol

### ISSUE THREAD

**Issue by camjac251** [zumoshi/BrowserSelect#18] opened 2016-11-16 10:06 UTC
I was able to set BrowserSelect as the default for HTTP but for all https:// links, it would go through whichever browser is set to default. Changing https to browserselect doesn't work.

**Comment by zumoshi** [comment] 2016-11-18 09:46
hello,
sorry for the late reply, i just saw the issue ...

I've just tested it with `https://google.com` on an IM app and browser select opened. have you tried setting another browser as default then using the `Set as default browser` button on the settings page of browser select to set it as default ?

if that didn't work try setting browser select as default for all the protocols it can handle from here:
`Start -> Settings -> System -> Default Apps -> Set Defaults by App, click on Firefox, then click "Set this program as default".`

if that still didn't work (unlikely) please post your os and registry settings at this address:
`HKEY_CURRENT_USER\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice `

**Comment by camjac251** [comment] 2016-11-18 13:08
After trying those steps, I was unable to get BrowserSelect to set itself as the default browser. After setting the browser as default I tried once with running browserselect as admin and one without, going to set as default browser. It changed http and https but http was set to microsoft edge and https was blank. I then went into Control Panel\Programs\Default Programs\Set Associations and tried setting BrowserSelect back to the default as http which worked before but it didn't apply the change this time.
I've attached below the registry settings for both http and https. For both, it's showing "(Default)" has a value of "(value not set)". My OS is Windows 10 Pro 64-bit with the latest stable updates.
[regkeys.tar.gz](https://github.com/zumoshi/BrowserSelect/files/599954/regkeys.tar.gz)

**Comment by zumoshi** [comment] 2016-11-18 14:41
that is strange. I don't have access to a windows 10 at the moment to test myself but I've never encountered this issue before.
can you try reinstalling browser select ? (do not run the installer as admin)

if that also fails to fix your issue then I'm out of ideas ...

---
if you managed to get it to work please share your solution here.

**Comment by JeffGillman** [comment] 2016-11-18 15:23
I'm using 64-bit Windows 10, current build. I was able to set BrowserSelect as default, and configure https://google.com to open in Firefox, and https://outlook.com to open in IE, and both worked every time thereafter. I did, however, have to get through these two things:
1. the first time I set BrowserSelect as default, a message popped up several seconds later saying that the default browser had changed to BrowserSelect but this had causes a problem, so Edge we set as the default (it was the not the default before that). 
2. So I brought up BrowserSelect again and set it as default, and then opened a URL from Start/Run, and was prompted by Windows for which browser I wanted as default. I chose BrowserSelect, and it's worked since then. 
Windows 10 default browser "protection" seems to be the issue.

**Comment by zumoshi** [comment] 2016-12-16 07:39
I have just tested on a clean install of windows 10. the first time a URL was opened after installing browserSelect the following screen showed up:

![image](https://cloud.githubusercontent.com/assets/4184939/21254979/4f2d537e-c37e-11e6-8d97-de335ce4b239.png)

after selecting browser select it was set as default for both `http` and `https`.

![image](https://cloud.githubusercontent.com/assets/4184939/21255023/8ebd0a52-c37e-11e6-8ec7-9db0dee90250.png)

I didn't even have to use the `set as default` option in settings. (that was mostly added for win7 , which does not have the prompt from the first image)
in the event that you missed the initial prompt you can set browserSelect as default from defaultPrograms section:

![image](https://cloud.githubusercontent.com/assets/4184939/21255193/91f8f02c-c37f-11e6-8e3e-29069c2ec8d6.png)
(click on image to view in full size)

so, I'm closing this issue because I was not able to reproduce it. but feel free to ask again if you still have trouble setting it as the default browser.

**Closed by zumoshi** 2016-12-16 07:39 UTC
